export enum BoardArticleCategory {
	FITNESS_TIPS = 'FITNESS_TIPS',
	NUTRITION = 'NUTRITION',
	WORKOUT_GUIDE = 'WORKOUT_GUIDE',
	CHALLENGE = 'CHALLENGE',
	SUCCESS_STORY = 'SUCCESS_STORY',
}

export enum BoardArticleStatus {
	ACTIVE = 'ACTIVE',
	DELETE = 'DELETE',
}
